# Generated by Django 2.1.7 on 2019-05-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_changed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
